# Generated by Django 4.2 on 2023-04-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_user_name_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='user',
        ),
    ]
