# Generated by Django 4.1.6 on 2023-03-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_comment_user_name_alter_post_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_pass',
        ),
    ]
