# Generated by Django 4.2 on 2023-04-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='born',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
