# Generated by Django 4.2 on 2023-04-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
