# Generated by Django 4.2 on 2023-04-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_img',
        ),
    ]
