# Generated by Django 4.2 on 2023-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.user_profile'),
        ),
    ]
