# Generated by Django 4.2 on 2023-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
