# Generated by Django 4.1.6 on 2023-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_comment_user_name_alter_post_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_img',
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.URLField(default='https://s26.picofile.com/file/8460931518/user_3_.png'),
        ),
    ]
