# Generated by Django 4.1.6 on 2023-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_post_user_img_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='profile_img/user_default.png', upload_to='profile_img'),
        ),
    ]
