# Generated by Django 4.1.6 on 2023-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='post_img/post_default.png', upload_to='post_img'),
        ),
    ]
