# Generated by Django 4.1.7 on 2023-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='', max_length=15),
        ),
    ]
