# Generated by Django 4.1.7 on 2023-04-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_user_profile_alter_comment_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='date_of_singup',
        ),
    ]
