# Generated by Django 4.1.6 on 2023-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_user_profile_date_of_singup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='born',
            field=models.DateField(default=''),
        ),
    ]
