# Generated by Django 4.2 on 2023-04-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_comment_user_name_alter_post_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
